[project]
requires-python = ">= 3.13"
dependencies = [
  "hypothesis==6.124.0",
]

[tool.pyright]
include = ["plugin.py"]
typeCheckingMode = "strict"

[tool.pyink]
line-length = 100
pyink-indentation = 2

[tool.flake8]
indent-size = 2
max-line-length = 100
exclude = ["__pycache__"]
doctests = true
