[project]
requires-python = ">= 3.13"
dependencies = [
	"requests",
	"tqdm",
]

[project.optional-dependencies]
dev = [
	"pyink",
	"pyright",
]

[tool.pyright]
include = ["plugin.py"]
typeCheckingMode = "strict"

[tool.pyink]
line-length = 100
pyink-indentation = 2

[tool.flake8]
indent-size = 2
max-line-length = 100
exclude = ["__pycache__"]
doctests = true


