from typing import Any, BinaryIO, Mapping, Protocol, Sequence

class Verify(Protocol):
  stderr: str | None
  problems: Sequence[Mapping[str, Any]]

class GPG:
  def __init__(self, gnupghome: str | None = ...) -> None: ...
  def __bool__(self) -> bool: ...
  def __nonzero__(self) -> bool: ...
  def import_keys_file(self, key_path: str) -> None: ...
  def verify_file(self, fileobj_or_path: BinaryIO, data_filename: str | None) -> Verify: ...
